kind: pipeline
name: smbclient

steps:
  - name: 4.10.8-r0
    image: plugins/docker
    settings:
      dockerfile: smbclient/Dockerfile
      build_args:
        - SAMBA_CLIENT_VERSION=4.10.8-r0
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD
      repo: codebreaker1/smbclient
      tags: [latest, 4.10.8]
