kind: pipeline
name: smbclient

steps:
  - name: 4.10.8
    image: plugins/docker
    settings:
      dockerfile: smbclient/Dockerfile
      build_args:
        - SAMBA_CLIENT_VERSION=4.10.8-r0
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD
      repo: codebreaker1/smbclient
      tags: [latest, 4.10.8]

---
kind: pipeline
name: curl

steps:
  - name: 7.66.0
    image: plugins/docker
    settings:
      dockerfile: curl/Dockerfile
      build_args:
        - CURL_VERSION=7.66.0-r0
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD
      repo: codebreaker1/curl
      tags: [latest, 7.66.0]

---
kind: pipeline
name: os-debianconsole

steps:
  - name: v1.5.4-python3
    image: plugins/docker
    settings:
      dockerfile: os-debianconsole/Dockerfile
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD
      repo: codebreaker1/os-debianconsole
      tags: [v1.5.4-python3]
