kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: smbclient/Dockerfile
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD
      repo: codebreaker1/smbclient
      tags: latest
